// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_batch_trainer_participant_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_batch_trainer_participant_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201809210502385_add_batch_trainer_participant_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
