// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_question_questionOption_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_question_questionOption_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201809290944094_add_question_questionOption_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
