// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_isDeleted_on_Trainer_Participant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isDeleted_on_Trainer_Participant));
        
        string IMigrationMetadata.Id
        {
            get { return "201809241854488_add_isDeleted_on_Trainer_Participant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
