// <auto-generated />
namespace DatabaseContexts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class check_migrate_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(check_migrate_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261750466_check_migrate_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
